from abc import ABC, abstractmethod
import logging

logger = logging.getLogger(__name__)


class BaseLLMClient(ABC):
    @abstractmethod
    def query(self, prompt: str, model: str = "default") -> str:
        pass


class MockLLMClient(BaseLLMClient):
    """A dummy client for testing logic without spending money."""

    def query(self, prompt: str, model: str = "default") -> str:
        logger.info(
            f"Mock LLM received prompt ({len(prompt)} chars). Returning dummy response."
        )
        return f"[[Mock Summary generated by {model} for prompt length {len(prompt)}]]"


# Simple Factory to get the client (we can expand this later to load your real client)
def get_llm_client(config: dict) -> BaseLLMClient:
    # In the future, check config['provider'] to return real Poe/Ollama client
    return MockLLMClient()
